/* empty css                      */import{S as a,N as d}from"./assets/vendor-wKantkHV.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function f(){new a(".reviews-swiper",{modules:[d],loop:!0,slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".reviews-nav .custom-next",prevEl:".reviews-nav .custom-prev"},observer:!0,observeParents:!0,breakpoints:{374:{slidesPerView:1.1,spaceBetween:20},1440:{slidesPerView:4,spaceBetween:20}}}),new a(".gallery-swiper",{modules:[d],loop:!0,slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",direction:"horizontal",navigation:{nextEl:".gallery-nav .custom-next",prevEl:".gallery-nav .custom-prev"},observer:!0,observeParents:!0,breakpoints:{374:{slidesPerView:1.1,spaceBetween:20},1440:{slidesPerView:4,spaceBetween:20}}})}document.addEventListener("DOMContentLoaded",f);document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),s=r.querySelector(".icon"),i=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="white" />
</svg>
    `,c=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#110C2C" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,s.innerHTML=t?c:o,t?u():l()}),n.forEach(m=>m.addEventListener("click",()=>{l(),s.innerHTML=o,t=!1})),window.addEventListener("scroll",p);function u(){i.style.display="block"}function l(){i.style.display="none"}function p(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function s(n){const e=document.getElementById(n);if(!e)return;const t=r(),o=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:o,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",t=>{const o=e.getAttribute("href"),c=o.split("#")[1];(o.startsWith("#")||o.startsWith("index.html#")||o.startsWith("/index.html#"))&&(t.preventDefault(),s(c))})});const n=window.location.hash;if(n){const e=n.substring(1),t=()=>{document.getElementById(e)?s(e):requestAnimationFrame(t)};setTimeout(t,100)}}});document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("cookie-popup"),s=document.getElementById("accept-cookies"),i=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(r.style.display="block"),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),r.style.display="none"}),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),r.style.display="none"})});
//# sourceMappingURL=index.js.map
